# **MORINGA SCHOOL IP WEEK 3 NORAH NAROH **

1.0 Importing the datasets to be used **bold text** **bold text**

In [5]:
#lets import the panda library
import pandas as pd
#as well as numpy library
import numpy as np

1.1 loading our data **sets** ***

In [6]:
#Loading our csv file into panda
df1 = pd.read_csv("/content/Telcom_dataset_1.csv")
df1

     PRODUCT  VALUE DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice      0   04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0   05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25   05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56   05:42.0  ...     19e2e      #NAME?      #NAME?
4      Voice     14   06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...       ...  ...       ...         ...         ...
4996     sms    100   01:54.0  ...     OTHER  0c2371d9bc  1e751d08a4
4997   Voice      1   01:54.0  ...     19e2e  5fb791cf56  65efe2bc62
4998   Voice      0   01:54.0  ...     19e2e  7773627c12  9ef9616350
4999   Voice      0   01:54.0  ...     19e2e  3f4af49d6c  969b8d0e39
5000   Voice      7   01:54.0  ...     19e2e  6f4d9b77a5  ebfc58af70

[5001 rows x 10 columns]

In [7]:
# loading telcom dataset 2
df2 = pd.read_csv("/content/Telcom_dataset_2.csv")
df2

     PRODUCT  VALUE DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0        sms      0   02:06.0  ...     19e2e  +854AcBQT2  +854AcBQT2
1      Voice      0   03:44.0  ...     19e2e  +854AcBQT2  +854AcBQT2
2        sms      0   04:06.0  ...     19e2e      #NAME?      #NAME?
3      Voice     37   04:48.0  ...     19e2e  /xvRrCVKoQ  /xvRrCVKoQ
4        sms     25   04:58.0  ...     19e2e      #NAME?      #NAME?
...      ...    ...       ...  ...       ...         ...         ...
4996     sms      0   01:53.0  ...     19e2e  896459aace  b7d00e59e4
4997     sms     25   01:53.0  ...     19e2e  7e90b35166  211015b14d
4998     sms      0   01:53.0  ...     19e2e  fe70e431df  c7ea989264
4999    data      0   01:53.0  ...     OTHER  ffa6759bb2         NaN
5000   Voice      0   01:53.0  ...     19e2e  8630058aca  b47a998a3e

[5001 rows x 10 columns]

In [8]:
#loading Telcom dataset for day 3
df3 = pd.read_csv("/content/Telcom_dataset_3.csv")
df3

     PRODUCT  VALUE DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice     61   01:28.0  ...     19e2e  +38u2u/rfx  +38u2u/rfx
1        sms      0   01:31.0  ...     19e2e      #NAME?      #NAME?
2      Voice     10   02:59.0  ...     19e2e  +ZaaZozy/+  +ZaaZozy/+
3        sms      0   03:04.0  ...     19e2e      #NAME?      #NAME?
4      Voice     22   03:16.0  ...     19e2e  /eeMklgyJA  /eeMklgyJA
...      ...    ...       ...  ...       ...         ...         ...
4996   Voice      0   01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62   01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32   01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30   01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60   01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[5001 rows x 10 columns]

1.2 MERGING THE THREE TABLES USING CONCAT

In [9]:
#merging the three tables using the vertical concat

df = pd.concat([df1,df2,df3],axis=0)
df

     PRODUCT  VALUE DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice      0   04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0   05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25   05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56   05:42.0  ...     19e2e      #NAME?      #NAME?
4      Voice     14   06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...       ...  ...       ...         ...         ...
4996   Voice      0   01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62   01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32   01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30   01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60   01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[15003 rows x 10 columns]

# 1.3 **Finding the null or the missing values **

In [ ]:
#checking the number of rows missing
df.isnull().sum()

PRODUCT               0
VALUE                 0
DATE_TIME             0
CELL_ON_SITE          0
DW_A_NUMBER_INT       0
DW_B_NUMBER_INT       0
COUNTRY_A             0
COUNTRY_B             0
CELL_ID               0
SITE_ID            1997
dtype: int64

In [10]:
#Checking if there are missing values in my data
df.isnull()

      PRODUCT  VALUE  DATE_TIME  ...  COUNTRY_B  CELL_ID  SITE_ID
0       False  False      False  ...      False    False    False
1       False  False      False  ...      False    False    False
2       False  False      False  ...      False    False    False
3       False  False      False  ...      False    False    False
4       False  False      False  ...      False    False    False
...       ...    ...        ...  ...        ...      ...      ...
4996    False  False      False  ...      False    False    False
4997    False  False      False  ...      False    False    False
4998    False  False      False  ...      False    False    False
4999    False  False      False  ...      False    False    False
5000    False  False      False  ...      False    False    False

[15003 rows x 10 columns]

In [11]:
#Dropping rows with missing values
df_no_missing = df.dropna()
df_no_missing

     PRODUCT  VALUE DATE_TIME  ... COUNTRY_B     CELL_ID     SITE_ID
0      Voice      0   04:37.0  ...     19e2e  /TJNe+Mmtu  /TJNe+Mmtu
1        sms      0   05:25.0  ...     19e2e  /+cKZKIp41  /+cKZKIp41
2        sms     25   05:41.0  ...     19e2e  /u0FSD+ahi  /u0FSD+ahi
3      Voice     56   05:42.0  ...     19e2e      #NAME?      #NAME?
4      Voice     14   06:29.0  ...     19e2e  051KhYDCpv  051KhYDCpv
...      ...    ...       ...  ...       ...         ...         ...
4996   Voice      0   01:43.0  ...     19e2e  2aa04dcab7  f7d63a29e5
4997   Voice     62   01:43.0  ...     19e2e  7f1f2f889f  b4ddb9e93c
4998   Voice     32   01:43.0  ...     19e2e  a4731e780e  d68260ef50
4999   Voice     30   01:43.0  ...     19e2e  98ed726da2  b4130b54ab
5000   Voice     60   01:43.0  ...     19e2e  1c11a2fcbb  6d70dae094

[13006 rows x 10 columns]

# 1.4  Analysis Of Data

In [12]:
df_no_missing['VALUE'].describe()

count    13006.000000
mean        27.304398
std        111.025088
min          0.000000
25%          0.000000
50%          0.000000
75%         25.000000
max       6750.000000
Name: VALUE, dtype: float64

In [13]:
grouped_df = df_no_missing.groupby(['VALUE']).max()
print(grouped_df['PRODUCT'])
grouped_df

VALUE
0         sms
1         sms
2         sms
3       Voice
4        data
        ...
2212    Voice
2330    Voice
3380    Voice
4212    Voice
6750    Voice
Name: PRODUCT, Length: 359, dtype: object

      PRODUCT DATE_TIME CELL_ON_SITE  ... COUNTRY_B     CELL_ID     SITE_ID
VALUE                                 ...
0         sms   59:58.0            _  ...     OTHER  ffcc507579  fff5ac6e3f
1         sms   59:01.0            _  ...     OTHER  fd8b1a4f29  fe91ac057a
2         sms   59:29.0            _  ...     OTHER  ffb86d66d2  fe32f3eba7
3       Voice   59:43.0            5  ...     19e2e  f8f987f764  fe91ac057a
4        data   59:28.0            _  ...     OTHER  ff7c503baf  ffa6bdc032
...       ...       ...          ...  ...       ...         ...         ...
2212    Voice   00:52.0            5  ...     OTHER  c68a1b9da4  969b8d0e39
2330    Voice   00:25.0            2  ...     OTHER  13c129b7fa  ea868b8a04
3380    Voice   00:07.0            2  ...     OTHER  5a7f6cf0fa  2e828e607c
4212    Voice   51:34.0            2  ...     OTHER  MpOhP3OKNN  MpOhP3OKNN
6750    Voice   00:23.0            2  ...     19e2e  3f5ac97214  a64fc672f1

[359 rows x 9 columns]

In [14]:
#importing the geo csv
df4 = pd.read_csv('/content/cells_geo.csv',sep = ";")
df4

      Unnamed: 0    VILLES      STATUS  ...          AREA     CELL_ID   SITE_CODE
0              0    ADJAME  In Service  ...           NaN  fbb2e75af3  0bb492ef17
1              1    ADJAME  In Service  ...           NaN  1502501d78  0bb492ef17
2              2    ADJAME  In Service  ...           NaN  0c2e182a0c  0bb492ef17
3              3   ASSINIE  In Service  ...           NaN  69bdfc69fd  8a1e6ce31f
4              4   ASSINIE  In Service  ...           NaN  7a1029d2ab  8a1e6ce31f
...          ...       ...         ...  ...           ...         ...         ...
3969        3969  ZUENOULA  In Service  ...  CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970        3970  ZUENOULA  In Service  ...  CENTRE NORTH  3ae1708153  f91ed8d2e9
3971        3971  ZUENOULA  In Service  ...  CENTRE NORTH  cb71f8a29c  61bee9c70c
3972        3972  ZUENOULA  In Service  ...  CENTRE NORTH  d4a6a0b645  61bee9c70c
3973        3973  ZUENOULA  In Service  ...  CENTRE NORTH  f9f3e42589  61bee9c70c

[3974 rows x 12 columns]

# 1.5 CLEANING THE GEO CSV DATA

In [15]:
#checking the number of missing values
df4.isnull().sum()

Unnamed: 0       0
VILLES           0
STATUS          67
LOCALISATION     0
DECOUPZONE       0
ZONENAME         6
LONGITUDE        0
LATITUDE         0
REGION           0
AREA            23
CELL_ID          0
SITE_CODE        0
dtype: int64

In [16]:
df4.isnull()

      Unnamed: 0  VILLES  STATUS  ...   AREA  CELL_ID  SITE_CODE
0          False   False   False  ...   True    False      False
1          False   False   False  ...   True    False      False
2          False   False   False  ...   True    False      False
3          False   False   False  ...   True    False      False
4          False   False   False  ...   True    False      False
...          ...     ...     ...  ...    ...      ...        ...
3969       False   False   False  ...  False    False      False
3970       False   False   False  ...  False    False      False
3971       False   False   False  ...  False    False      False
3972       False   False   False  ...  False    False      False
3973       False   False   False  ...  False    False      False

[3974 rows x 12 columns]

In [17]:
df_no_missing1 = df4.dropna()
df_no_missing1

      Unnamed: 0    VILLES      STATUS  ...           AREA     CELL_ID   SITE_CODE
23            23     ABOBO  In Service  ...  ABIDJAN NORTH  f740406877  0f34c36ac5
24            24     ABOBO  In Service  ...  ABIDJAN NORTH  959e54c8f7  0f34c36ac5
25            25     ABOBO  In Service  ...  ABIDJAN NORTH  56b7e7000c  0f34c36ac5
26            26     ABOBO  In Service  ...  ABIDJAN NORTH  bc51c17a6f  0f34c36ac5
27            27     ABOBO  In Service  ...  ABIDJAN NORTH  e460975c9f  0f34c36ac5
...          ...       ...         ...  ...            ...         ...         ...
3969        3969  ZUENOULA  In Service  ...   CENTRE NORTH  1cfc2d7ab1  f91ed8d2e9
3970        3970  ZUENOULA  In Service  ...   CENTRE NORTH  3ae1708153  f91ed8d2e9
3971        3971  ZUENOULA  In Service  ...   CENTRE NORTH  cb71f8a29c  61bee9c70c
3972        3972  ZUENOULA  In Service  ...   CENTRE NORTH  d4a6a0b645  61bee9c70c
3973        3973  ZUENOULA  In Service  ...   CENTRE NORTH  f9f3e42589  61bee9c70c

[3880 rows x 12 columns]

# 1.6 Analyzing geo csv file data

In [18]:
#Analysing its data
df_no_missing1['VILLES'].describe()

count       3880
unique       501
top       COCODY
freq         354
Name: VILLES, dtype: object

In [19]:
grouped_df =df_no_missing1.groupby(['VILLES']).max()
print(grouped_df['STATUS'])
grouped_df

VILLES
ABENGOUROU       In Service
ABOBO            In Service
ABOISSO          In Service
ABOISSO COMOE    In Service
ABONGOUA         In Service
                    ...
ZATTA            In Service
ZIKISSO          In Service
ZON-HOUNIEN      In Service
ZOUKOUGBEU       In Service
ZUENOULA         In Service
Name: STATUS, Length: 501, dtype: object

               Unnamed: 0      STATUS  ...     CELL_ID   SITE_CODE
VILLES                                 ...
ABENGOUROU             64  In Service  ...  ff33a69318  aa2d7103fc
ABOBO                3461  In Service  ...  ffa0b81471  fb35d6b5d3
ABOISSO               176  In Service  ...  f41bac45e0  d52bb03161
ABOISSO COMOE         157  In Service  ...  ff4372eafb  640427c4c9
ABONGOUA              179  In Service  ...  d1a1270467  a8d8462dda
...                   ...         ...  ...         ...         ...
ZATTA                3943  In Service  ...  eb42ca8859  c644d1ce4c
ZIKISSO              3947  In Service  ...  98a71b5af2  211015b14d
ZON-HOUNIEN          3962  In Service  ...  ff3bdca4e3  32b8357a82
ZOUKOUGBEU           3965  In Service  ...  eee63aed85  443ac3fc19
ZUENOULA             3973  In Service  ...  f9f3e42589  f91ed8d2e9

[501 rows x 11 columns]